# Generated by Django 5.1.1 on 2024-09-30 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cart_caritem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productphotos',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product'),
        ),
    ]
